# ini untuk print true false
print(true);

var a = 1;
var b = "str";
var c = 10 + 5 * 2;
var d = a + 10;
print(a);
print(b);
print(c);
print(d);
print(100);
print("oi");

var arr = [91, 24, 51, 39];
print("arr: ");
print(arr);

print("arr[1]: ");
print(arr[1]);

print("arr[a]: ");
print(arr[a]);


fun add(first, second){
    return first + second;
}

# fun hello(){
#     print("hello");
# }

print(add(4, 9));
# hello();