print(10);
print(10 + 5);
print(10 - 2);
print(10 * 4);
print(10 / 2);
# print(10 % 3);
print(10 * 4 / 2 + 1);
print("hello world");

var x = 888;
var y = 9987;
print(x);
print(y);

var z = "str";
print(z);


print(false);
var boolean = true;
print(boolean);

# print(10.5);
# var float = 10.5 + 2.3;




var first = 90;
var second = 90;

print(first < second);

# print(!90);









var sum = x + y;
# print(sum);